name: flutter_installer
description: Flutter Installer is an installer for Flutter built with Flutter.
version: 0.0.6+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # stacked
  stacked: ^1.7.6

  # third-party services
  stacked_services: ^0.5.4+3

  # navigation
  auto_route: ^0.6.7

  # inversion of control
  get_it: ^4.0.4
  injectable: ^1.0.4

  # icons
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1

  # ui
  percent_indicator: ^2.1.7+3
  flutter_markdown: ^0.4.4
  theme_mode_handler: ^2.0.0

  # accesses filesystem
  process_run: ^0.11.0+2
  path_provider: ^1.6.18
  shared_preferences: ^0.5.12

  # misc
  logger: ^0.9.3
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 8ea9f1ce79f04e44bd6392f4155a014b0a7eb6e8
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 8ea9f1ce79f04e44bd6392f4155a014b0a7eb6e8

  url_launcher: ^5.7.2

  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.2
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app_logos/
    - assets/misc/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
