name: flutter_installer
description: Flutter Installer is an installer for Flutter built with Flutter.
version: 0.0.7+7
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # stacked
  stacked: ^1.7.7

  # third-party services
  stacked_services: ^0.6.0+1

  # navigation
  auto_route: ^0.6.9

  # inversion of control
  get_it: ^5.0.4
  injectable: ^1.0.7

  # icons
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.11.0

  # ui
  percent_indicator: ^2.1.9
  flutter_markdown: ^0.5.2
  theme_mode_handler: ^2.0.0

  # accesses filesystem
  process_run: ^0.11.2+8
  path_provider: ^1.6.27
  shared_preferences: ^0.5.12+4

  # misc
  logger: ^0.9.4
  url_launcher: ^5.7.10
  http: ^0.12.2
  file_selector: ^0.7.0+2
  file_selector_windows: ^0.0.1
  file_selector_macos: ^0.0.1
  file_selector_linux: ^0.0.1
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  async: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.13
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app_logos/
    - assets/misc/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
