name: flutter_installer
description: Flutter Installer is an installer for Flutter built with Flutter.
version: 0.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^0.1.3
  # Stacked
  stacked: ^1.7.6
  # third-party services
  stacked_services: ^0.5.2
  # navigation
  auto_route: ^0.6.7
  # inversion of control
  get_it: ^4.0.4
  injectable: ^1.0.4
  # Logger
  logger: ^0.9.2

  # Data Persistence
  shared_preferences: ^0.5.8

  # MISC
  percent_indicator: ^2.1.5
  path_provider: ^1.6.11
  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c
  url_launcher: ^5.5.0
  url_launcher_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde
      ref: 9e9b68b67c2a2c0b82eed2224f709aff2ccbab7c
  flutter_markdown: ^0.4.3
  process_run: ^0.10.12+1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.8
  injectable_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/app_logos/
    - assets/misc/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700
