name: flutter_installer
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^0.1.3
  # Stacked
  stacked: ^1.7.1+1
  # third-party services
  stacked_services: ^0.4.4+3
  # navigation
  auto_route: ^0.6.1
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  # Flutter Spinkit
  flutter_spinkit: ^4.1.2+1
  # Logger
  logger: ^0.9.1

  # MISC
  google_fonts: ^1.1.0
  path_provider: ^1.6.11
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 282bb7b172a42a1f4b573540cc19e7610a867a93
  path_provider_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
      ref: 282bb7b172a42a1f4b573540cc19e7610a867a93
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 282bb7b172a42a1f4b573540cc19e7610a867a93

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.0
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
